# Generated by Django 3.2.17 on 2023-03-01 16:25

from django.db import migrations, models
import osis_comment.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
            ],
            bases=(osis_comment.models.mixins.CommentDeleteMixin, models.Model),
        ),
    ]
