# Generated by Django 3.2.17 on 2023-03-01 16:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0647_merge_20230113_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEntry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('object_uuid', models.UUIDField(db_index=True, verbose_name="Registered object's UUID")),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Tags')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra data')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.person')),
            ],
            options={
                'verbose_name': 'Comment entry',
                'verbose_name_plural': 'Comment entries',
                'ordering': ('-created_at',),
            },
        ),
    ]
