# Generated by Django 3.2.18 on 2023-04-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commententry',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
