# Generated by Django 3.2.18 on 2023-04-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_comment', '0002_commententry_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commententry',
            options={'ordering': ('-modified_at',), 'verbose_name': 'Comment entry', 'verbose_name_plural': 'Comment entries'},
        ),
    ]
