name: Frontend

on:
  pull_request:
    branches: [dev]

jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.7
#      - name: Install Dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      - name: Run Tests
#        run: |
#          python manage.py test osis_comment

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - run: npm install
    - run: npm run lint

  tests_coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache npm dependencies
      uses: actions/cache@v2
      with:
        path: '~/.npm'
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - run: |
        npm install
        npm install coveralls
    - run: npm run coverage
